version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/db:/tmp/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce_development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_cache:/rails/tmp/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  # Optional: Mailcatcher for development email testing
  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    profiles:
      - mail

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules:
  rails_cache: